import { motion } from 'framer-motion'

const EASE = [0.16, 1, 0.3, 1] as const

const stats = [
  { value: '42%', label: 'of storage facilities have no active digital marketing strategy' },
  { value: '3\u00d7', label: 'more revenue generated by facilities with automated pricing' },
  { value: '$180k', label: 'average annual revenue left on the table without optimization' },
]

export function ProblemSection() {
  return (
    <section className="relative z-10 py-24 px-4 bg-[#070B14] border-t border-[#1E2A42]">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, ease: EASE }}
          className="mb-14"
        >
          <p className="text-xs font-semibold tracking-[0.15em] uppercase text-[#F97316] mb-3">The Problem</p>
          <h2 className="text-3xl sm:text-4xl font-bold text-[#F1F5F9] max-w-2xl leading-[1.1]">
            Most storage facilities are leaving revenue on the table
          </h2>
        </motion.div>

        <div className="grid sm:grid-cols-3 gap-6">
          {stats.map((stat, i) => (
            <motion.div
              key={stat.value}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.08, ease: EASE }}
              className="bg-[#0D1220] rounded-xl p-6 border border-[#1E2A42] pl-7"
              style={{ borderLeft: '2px solid #F97316' }}
            >
              <p className="text-6xl font-bold text-[#F1F5F9] mb-3 leading-none">{stat.value}</p>
              <p className="text-sm text-[#94A3B8] leading-relaxed">{stat.label}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
